### ISSUE TITLE
`tro setup` errors ("Unable to validate credentials.")

### ISSUE THREAD

**Issue by joshtriplett** [MichaelAquilina/trello-rs#28]
I created a developer API key, provided the key and token to `tro setup`, and got "Unable to validate credentials. Please re-check and try again".

Happy to provide further information to help debug this.

**Comment by MichaelAquilina** [comment]
Hi @joshtriplett, the comnand should work fine 🤔 

An alternative you can try is to manually define the configuration file that it creates yourself to see if that works.

Under `~/.config/tro/config.toml`

with the format:

```toml
host = "https://api.trello.com"
token = "xxxxxx"
key = "xxxxx"
```
